"""Initial_migration

Revision ID: 36af8e3b39ce
Revises: 
Create Date: 2025-12-26 07:57:46.818182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '36af8e3b39ce'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_question_category', table_name='question_analytics')
    op.drop_index('idx_question_type', table_name='question_analytics')
    op.alter_column('user_feedback', 'workflow_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('user_feedback', 'submitted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_feedback_workflow', table_name='user_feedback')
    op.drop_constraint('user_feedback_workflow_id_fkey', 'user_feedback', type_='foreignkey')
    op.alter_column('workflow_steps', 'workflow_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('workflow_steps', 'executed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_steps_agent', table_name='workflow_steps')
    op.drop_index('idx_steps_workflow', table_name='workflow_steps')
    op.drop_constraint('workflow_steps_workflow_id_fkey', 'workflow_steps', type_='foreignkey')
    op.alter_column('workflows', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('workflows', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_workflows_created', table_name='workflows')
    op.drop_index('idx_workflows_status', table_name='workflows')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_workflows_status', 'workflows', ['status'], unique=False)
    op.create_index('idx_workflows_created', 'workflows', [sa.text('created_at DESC')], unique=False)
    op.alter_column('workflows', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('workflows', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_foreign_key('workflow_steps_workflow_id_fkey', 'workflow_steps', 'workflows', ['workflow_id'], ['id'], ondelete='CASCADE')
    op.create_index('idx_steps_workflow', 'workflow_steps', ['workflow_id'], unique=False)
    op.create_index('idx_steps_agent', 'workflow_steps', ['agent_name'], unique=False)
    op.alter_column('workflow_steps', 'executed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('workflow_steps', 'workflow_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_foreign_key('user_feedback_workflow_id_fkey', 'user_feedback', 'workflows', ['workflow_id'], ['id'], ondelete='CASCADE')
    op.create_index('idx_feedback_workflow', 'user_feedback', ['workflow_id'], unique=False)
    op.alter_column('user_feedback', 'submitted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_feedback', 'workflow_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index('idx_question_type', 'question_analytics', ['request_type'], unique=False)
    op.create_index('idx_question_category', 'question_analytics', ['question_category'], unique=False)
    # ### end Alembic commands ###
