"""add_vectors

Revision ID: 4a4322b085bf
Revises: 36af8e3b39ce
Create Date: 2025-12-26 19:48:49.604562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4a4322b085bf'
down_revision: Union[str, None] = '36af8e3b39ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_analytics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('question_category', sa.String(length=50), nullable=True),
    sa.Column('question_embedding', pgvector.sqlalchemy.Vector(dim=1536), nullable=True),
    sa.Column('request_type', sa.String(length=100), nullable=True),
    sa.Column('avg_rating', sa.DECIMAL(precision=3, scale=2), nullable=True),
    sa.Column('times_asked', sa.Integer(), nullable=True),
    sa.Column('times_helpful', sa.Integer(), nullable=True),
    sa.Column('last_used', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_feedback',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('questions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('responses', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('question_ratings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('approval_status', sa.String(length=20), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflow_steps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('agent_name', sa.String(length=100), nullable=False),
    sa.Column('input_state', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=True),
    sa.Column('output_state', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.DECIMAL(precision=10, scale=6), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflows',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_request', sa.Text(), nullable=False),
    sa.Column('request_embedding', pgvector.sqlalchemy.Vector(dim=1536), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('state', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('final_output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workflows')
    op.drop_table('workflow_steps')
    op.drop_table('user_feedback')
    op.drop_table('question_analytics')
    # ### end Alembic commands ###
